services:
  todo.api.dev:
    image: todo.api.dev
    hostname: todo.api.dev
    build:
      context: .
      dockerfile: ToDo.API/Dockerfile.dev
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend

  database:
    image: postgres
    hostname: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U root'" ]
      interval: 10s
      timeout: 3s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  backend:
    driver: bridge