FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

COPY ["ToDo.API/ToDo.API.csproj", "ToDo.API/"]
COPY ["ToDo.Application/ToDo.Application.csproj", "ToDo.Application/"]
COPY ["ToDo.Persistence/ToDo.Persistence.csproj", "ToDo.Persistence/"]
RUN dotnet restore "ToDo.API/ToDo.API.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 8080
EXPOSE 8081

CMD ["dotnet", "run", "--project", "ToDo.API/ToDo.API.csproj", "-c", "Debug"]
