FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /app

COPY ["ToDoApp.API/ToDoApp.API.csproj", "ToDoApp.API/"]
COPY ["ToDoApp.Application/ToDoApp.Application.csproj", "ToDoApp.Application/"]
COPY ["ToDoApp.Persistence/ToDoApp.Persistence.csproj", "ToDoApp.Persistence/"]

RUN dotnet restore "ToDoApp.API/ToDoApp.API.csproj"
COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT ["dotnet", "ToDoApp.API.dll"]